# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
sudo: required

language: go

rvm:
  - 2.3

services:
  - docker

env:
  - TERRAFORM_VERSION=0.11.1 IMAGE_NAME=terraform-azure-database-module

jobs:
  include:
    - stage: go test
      install: true
      script:
      - docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} -t ${IMAGE_NAME} .
      - docker run ${IMAGE_NAME} bash -c "export GOPATH=$HOME/go && export PATH=$PATH:$GOROOT/bin:$GOPATH/bin"
      - docker run ${IMAGE_NAME} bash -c "go get github.com/denisenkom/go-mssqldb"
      - docker run ${IMAGE_NAME} bash -c "go get github.com/gruntwork-io/terratest/modules/retry"
      - docker run ${IMAGE_NAME} bash -c "go get github.com/gruntwork-io/terratest/modules/terraform"
      - docker run ${IMAGE_NAME} bash -c "cd terratest/sql && go test"