# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
sudo: required

language: ruby

rvm:
  - 2.3

services:
  - docker

env:
  - TERRAFORM_VERSION=0.11.5 IMAGE_NAME=terraform-azure-database-module

jobs:
  include:
    - stage: go test
      install: true
      script:
      - docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} -t ${IMAGE_NAME} .
      - docker run ${IMAGE_NAME} bash -c "export GOPATH=$HOME/terratest && export PATH=$PATH:/usr/local/go/bin && go get github.com/denisenkom/go-mssqldb && go get github.com/gruntwork-io/terratest/modules/retry && go get github.com/gruntwork-io/terratest/modules/terraform && cd terratest/sql && go test"